services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    ports:
      - "8765:8765"
    volumes:
      - ./docs:/docs/docs
      - ./mkdocs.yml:/docs/mkdocs.yml
    restart: unless-stopped
